Mmap error handling
tbricks/tbstack pull request #7
Opened 2016-09-09 17:20 UTC by credmon

Add error handling for memory mapped chunks to make sure we don't attempt to access memory mapped regions that are beyond the length of the memory mapped file, but within the memory mapped chunk. Accessing beyond the end of a memory mapped file can cause a SIGBUS.

Also remove what appears to be useless debug.

2016-09-20 14:39 UTC, v-nikulichev commented on src/mem_map.c
> +        fprintf(stderr, "mmap length > size - offset (%d > %d), truncating "
Should we always print this message? It seems to be a problem within a program, not ours.

2016-09-20 14:40 UTC, v-nikulichev requested changes

2016-09-20 15:30 UTC, credmon commented on src/mem_map.c
> +        fprintf(stderr, "mmap length > size - offset (%d > %d), truncating "
Sure, we can remove this message.

2016-09-20 15:38 UTC, credmon commented on src/mem_map.c
> +        fprintf(stderr, "mmap length > size - offset (%d > %d), truncating "
OK, that message has been removed, and I squashed, rebased, and pushed the change.

2016-09-21 00:46 UTC, v-nikulichev commented on src/mem_map.c
> +        fprintf(stderr, "mmap offset too large (%d > %d)\n", region->offset, stat_buf.st_size);
Format `%d` is wrong here. Shouldn't we remove this message too?

2016-09-21 00:46 UTC, v-nikulichev requested changes

2016-09-21 20:16 UTC, credmon commented on src/mem_map.c
> +        fprintf(stderr, "mmap offset too large (%d > %d)\n", region->offset, stat_buf.st_size);
Sure, we can remove it.

2016-09-21 20:19 UTC, credmon commented on src/mem_map.c
> +        fprintf(stderr, "mmap offset too large (%d > %d)\n", region->offset, stat_buf.st_size);
I've removed that comment, squashed the commit and pushed the changes.

2016-09-21 20:38 UTC, v-nikulichev commented
Thanks!

2016-09-21 20:38 UTC, merged